version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: legalagent_backend
    env_file:
      - .env
    volumes:
      # Mount mã nguồn để live-reload khi phát triển local
      - ./backend/app:/app/app 
      # Mount data và logs để dữ liệu được lưu trữ bên ngoài container
      - ./data:/app/data  
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: legalagent_frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8501:8501"
    environment:
      # Frontend sẽ giao tiếp với backend qua tên service 'backend' trong mạng Docker
      - BACKEND_API_URL=http://backend:8000
      # Truyền API Key vào môi trường của container frontend để nó có thể tự nạp
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
       # Mount mã nguồn để live-reload khi phát triển local
      - ./frontend:/app
